In [1]:
import numpy as np
import pandas as pd
import glob
import re
import os
import requests
from plotnine import *

In [2]:
# set up connection to hugging face to read in data
repo = "boettiger-lab/rl4eco"
base_path = "rl4greencrab/data/rl_policies"
subfolders = ["size-time", "count", "count-biomass-time", "count-time"]
api_base = f"https://huggingface.co/api/models/{repo}/tree/main/"
resolve_base = f"https://huggingface.co/{repo}/resolve/main/"

# get list of csv files across all subfolders via the API
csv_paths = []
for sub in subfolders:
    listing = requests.get(f"{api_base}{base_path}/{sub}").json()
    csv_paths += [f["path"] for f in listing
                  if f["type"] == "file" and f["path"].endswith(".csv")]

In [3]:
# read in rl simulation data and add metadata columns
frames = []
for path in csv_paths:
    df = pd.read_csv(f"{resolve_base}{path}")
    df = df[df['t'] == 99]  # subset by t value
    filename = os.path.basename(path)

    # Parse filename: {algorithm}_{obs_type}_sim_{replicate}.csv
    match = re.match(r'([^_]+)_(.+)_sim_(\d+)\.csv', filename)
    algorithm = match.group(1)        # e.g., 'td3'
    obs_type  = match.group(2)        # e.g., 'count-time'
    replicate = int(match.group(3))   # e.g., 3

    df["algorithm"]   = algorithm
    df["obs_type"]    = obs_type
    df["replicate"]   = replicate
    frames.append(df)

combined_df = pd.concat(frames, ignore_index=True)

In [4]:
# 1. Group by algorithm and obs_type, mean and variance of rew
summary1 = (combined_df
    .groupby(['algorithm', 'obs_type'])['rew']
    .agg(mean_rew='mean', var_rew='var')
    .reset_index()
)

# 2. First average within each replicate, then mean and variance across replicates
summary2 = (combined_df
    .groupby(['algorithm', 'obs_type', 'replicate'])['rew']
    .mean()
    .reset_index()
    .rename(columns={'rew': 'mean_rew'})
    .groupby(['algorithm', 'obs_type'])['mean_rew']
    .agg(mean_rew='mean', var_rew='var')
    .reset_index()
)

In [7]:
# save summaries
summary1.to_csv("../data/reward/reward_summary_all.csv", index=False)
summary2.to_csv("../data/reward/reward_summary_withinrep.csv", index=False)

In [5]:
summary1

   algorithm            obs_type   mean_rew    var_rew
0        ppo               count  -7.839712   3.226293
1        ppo  count-biomass-time  -7.655120   6.419178
2        ppo          count-time  -8.556171   9.003671
3        ppo           size-time  -8.194557   3.316351
4        td3               count -12.406705  39.291344
5        td3  count-biomass-time  -7.920903   3.431521
6        td3          count-time -16.177410  38.445420
7        td3           size-time -13.221938  26.929622
8        tqc               count  -9.512286  10.418472
9        tqc  count-biomass-time  -7.533753   2.907288
10       tqc          count-time  -9.589675   6.050933
11       tqc           size-time  -9.059437   6.663188

In [6]:
summary2

   algorithm            obs_type   mean_rew    var_rew
0        ppo               count  -7.839712   0.247467
1        ppo  count-biomass-time  -7.655120   1.379700
2        ppo          count-time  -8.556171   2.480843
3        ppo           size-time  -8.194557   0.372903
4        td3               count -12.406705  36.575769
5        td3  count-biomass-time  -7.920903   0.352993
6        td3          count-time -16.177410  32.513934
7        td3           size-time -13.221938  28.103821
8        tqc               count  -9.512286   8.001038
9        tqc  count-biomass-time  -7.533753   0.028638
10       tqc          count-time  -9.589675   0.528439
11       tqc           size-time  -9.059437   1.349586

In [13]:
# get best TQC replicate
(
    combined_df[combined_df['algorithm'] == 'tqc'].
    groupby(['algorithm', 'obs_type', 'replicate'])['rew'].mean().idxmax()
)

('tqc', 'count-biomass-time', np.int64(3))